services:
  vscode-ssh:
    build: . # 在当前目录构建镜像
    # image: code_offline:0.0.1
    container_name: container_code_offline
    ports:
      - "2222:22" # 将宿主机的 2222 端口映射到容器的 22 端口
    # volumes:
    # 如果你修改了 Dockerfile 使用密钥登录，并需要设置 root 用户的 SSH 密钥
    # - ~/.ssh:/root/.ssh # 挂载宿主机的 SSH 密钥到容器的 root 用户 SSH 目录 (如果使用密钥登录)
    # 也可以使用 code_online.Dockerfile 构建的镜像 挂在本地的linux版本的code server文件（目录结构保持一致）
    # - ./vscode_server_data:/home/vscode/.vscode-server
    restart: unless-stopped
    command: ["/usr/sbin/sshd", "-D"] # CMD 已经设置了，但是这里需要覆盖
